(function(){
  function identifyCalendarCards(){
    document.querySelectorAll('.cal-event').forEach(card=>{
      if(card.dataset.recordReady)return;
      const time=(card.querySelector('.cal-time')?.textContent||'').split('–'),org=(card.querySelector('.cal-org')?.textContent||'').trim(),title=(card.children[2]?.textContent||'').trim();
      const cell=card.closest('.cal-cell,.cal-day,.cal-term-day');let date='';
      if(cell?.classList.contains('cal-cell')){const num=Number(cell.querySelector('.num')?.textContent);if(num){const anchor=document.getElementById('calAnchor')?.value||'';const [y,m]=anchor.split('-').map(Number);let mm=m,yy=y;if(cell.classList.contains('out')){if(num>20){mm=m-1;if(mm<1){mm=12;yy--}}else{mm=m+1;if(mm>12){mm=1;yy++}}}date=`${yy}-${String(mm).padStart(2,'0')}-${String(num).padStart(2,'0')}`}}
      if(cell?.classList.contains('cal-day')){const anchor=document.getElementById('calAnchor')?.value;if(anchor){const d=new Date(anchor+'T12:00:00'),target=[...document.querySelectorAll('.cal-day')].indexOf(cell),shift=(d.getDay()+6)%7,start=new Date(d.getTime()-shift*86400000);date=new Date(start.getTime()+target*86400000).toISOString().slice(0,10)}}
      if(cell?.classList.contains('cal-term-day')){const txt=cell.querySelector('.cal-term-date')?.textContent||'';const d=new Date(txt+' 12:00');if(!isNaN(d))date=d.toISOString().slice(0,10)}
      if(!date)return;
      const b=B.find(x=>x.booking_date===date&&String(x.start_time||'').slice(0,5)===time[0]&&String(x.end_time||'').slice(0,5)===time[1]&&(x.title||'Booking')===title&&(hn(x.hirer_id)||'School/Internal')===org);
      if(b){card.dataset.bookingId=b.id;card.dataset.recordReady='1';return}
      const dow=new Date(date+'T12:00:00').getDay();for(const p of G){if(p.active===false||p.starts_on>date||p.ends_on<date||(hn(p.hirer_id)||'School/Internal')!==org)continue;const s=RS.find(x=>x.programme_id===p.id&&x.active!==false&&Number(x.day_of_week)===dow&&String(x.start_time||'').slice(0,5)===time[0]&&String(x.end_time||'').slice(0,5)===time[1]&&(x.title||p.name||'Recurring booking')===title);if(s){card.dataset.programmeId=p.id;card.dataset.sessionId=s.id;card.dataset.recordReady='1';break}}
    })
  }
  window.calendarEditEvent=function(btn){const card=btn.closest('.cal-event');identifyCalendarCards();if(card.dataset.bookingId)return editBooking(card.dataset.bookingId);if(card.dataset.sessionId)return editSession(card.dataset.sessionId,card.dataset.programmeId);alert('This calendar item could not be matched to its booking record.')};
  window.calendarManageRecurring=function(btn){
    const card=btn.closest('.cal-event');identifyCalendarCards();const pid=card.dataset.programmeId;if(!pid)return alert('This recurring session could not be matched.');
    OPEN_PROG=pid;
    document.querySelectorAll('.booking-panel').forEach(x=>x.classList.remove('on'));
    document.querySelectorAll('.booking-tab').forEach(x=>x.classList.remove('active'));
    const panel=document.getElementById('bookingTabRecurring');if(panel){panel.classList.add('on');[...panel.children].forEach(ch=>ch.style.display='')}
    document.querySelector('.booking-tab[data-btab="recurring"]')?.classList.add('active');
    const rbSite=document.getElementById('rbSite'),rbOrg=document.getElementById('rbOrg'),rbSearch=document.getElementById('rbSearch'),rbStatus=document.getElementById('rbStatus');
    const p=G.find(g=>g.id===pid);if(rbSearch)rbSearch.value='';if(rbSite&&p)rbSite.value=p.site_id||'';if(rbOrg&&p)rbOrg.value=p.hirer_id||'internal';if(rbStatus)rbStatus.value='active';
    renderRecurringBookings();
    setTimeout(()=>{const target=[...document.querySelectorAll('.rb-item')].find(el=>(el.querySelector('button[onclick*="manageProgramme"]')?.getAttribute('onclick')||'').includes(pid));target?.scrollIntoView({behavior:'smooth',block:'center'})},80)
  };
  function addCalendarActions(){identifyCalendarCards();document.querySelectorAll('.cal-event').forEach(card=>{if(card.querySelector('.cal-event-actions'))return;const isRecurring=!!card.dataset.programmeId;const actions=document.createElement('div');actions.className='cal-event-actions';actions.innerHTML=`<button type=button onclick="event.stopPropagation();calendarEditEvent(this)">Edit</button>${isRecurring?'<button type=button onclick="event.stopPropagation();calendarManageRecurring(this)">Manage series</button>':''}`;card.appendChild(actions)})}
  const priorCal=window.renderBookingCalendar;window.renderBookingCalendar=function(){priorCal();setTimeout(addCalendarActions,0)};
  const panels=[['recurring','bookingTabRecurring','Recurring Bookings'],['single','bookingTabSingle','Single Booking'],['school','bookingTabSchool','School Events'],['income','bookingTabIncome','Pool Usage & Income']],collapsed={};window.toggleBookingSection=function(name){collapsed[name]=!collapsed[name];applyCollapsibleSections()};function applyCollapsibleSections(){panels.forEach(([name,id,label])=>{const panel=document.getElementById(id);if(!panel)return;let bar=panel.querySelector(':scope > .section-collapse-bar');if(!bar){bar=document.createElement('div');bar.className='section-collapse-bar';bar.innerHTML=`<button type=button onclick="toggleBookingSection('${name}')"><span class=section-chevron>▾</span> ${label}</button>`;panel.insertBefore(bar,panel.firstChild)}bar.querySelector('.section-chevron').textContent=collapsed[name]?'▸':'▾';[...panel.children].forEach(ch=>{if(ch!==bar)ch.style.display=collapsed[name]?'none':''})})}const priorTab=window.setBookingTab;window.setBookingTab=function(name){priorTab(name);setTimeout(applyCollapsibleSections,0)};const priorRender=window.render;window.render=function(){priorRender();setTimeout(applyCollapsibleSections,0)};window.addEventListener('load',()=>setTimeout(applyCollapsibleSections,150));const style=document.createElement('style');style.textContent=`.cal-event{position:relative}.cal-event-actions{display:flex;gap:4px;flex-wrap:wrap;margin-top:5px}.cal-event-actions button{border:0;background:#fff;border-radius:5px;padding:3px 6px;font-size:10px;cursor:pointer;box-shadow:0 0 0 1px rgba(15,60,90,.15)}.cal-event-actions button:hover{background:#eef5fa}.section-collapse-bar{display:flex;justify-content:flex-end;margin:0 0 8px}.section-collapse-bar button{border:1px solid #d9e2ea;background:#f6f9fb;border-radius:7px;padding:6px 10px;font-weight:600;cursor:pointer;color:#173b57}.section-chevron{display:inline-block;width:14px}`;document.head.appendChild(style)
})();