(function(){
const DAY=86400000;
let BILL_BATCHES=[],BILL_EVENTS=[];
function billIso(d){let y=d.getFullYear(),m=String(d.getMonth()+1).padStart(2,'0'),day=String(d.getDate()).padStart(2,'0');return `${y}-${m}-${day}`}
function billParse(v){return new Date(v+'T12:00:00')}
function billHours(a,b){let x=String(a||'00:00').split(':').map(Number),y=String(b||'00:00').split(':').map(Number);return Math.max(0,(y[0]*60+y[1]-x[0]*60-x[1])/60)}
function billMoney(v){return '£'+Number(v||0).toLocaleString('en-GB',{minimumFractionDigits:2,maximumFractionDigits:2})}
function monthBounds(v){let [y,m]=v.split('-').map(Number),from=new Date(y,m-1,1,12),to=new Date(y,m,0,12);return {from:billIso(from),to:billIso(to),usage_month:billIso(from)}}
function monthLabel(v){let [y,m]=v.split('-').map(Number);return new Date(y,m-1,1,12).toLocaleDateString('en-GB',{month:'long',year:'numeric'})}
function vatRate(hirerId){return Number(H.find(h=>h.id===hirerId)?.vat_rate||20)}
function billBreak(pid,date){return BR.some(b=>b.programme_id===pid&&b.starts_on<=date&&(b.ends_on||b.starts_on)>=date)}
function billCancelled(pid,sid,date){return EX.some(x=>x.programme_id===pid&&x.exception_date===date&&x.session_id===sid)}
function monthRows(hirerId,siteId,month){
 let {from,to}=monthBounds(month),out=[];
 G.filter(p=>p.active!==false&&p.hirer_id===hirerId&&p.site_id===siteId&&p.starts_on<=to&&p.ends_on>=from).forEach(p=>{
  let start=p.starts_on>from?p.starts_on:from,end=p.ends_on<to?p.ends_on:to;
  RS.filter(s=>s.programme_id===p.id&&s.active!==false&&(s.charge_type||'chargeable')==='chargeable').forEach(s=>{
   let d=billParse(start),last=billParse(end);
   while(d<=last){if(d.getDay()===Number(s.day_of_week)){let date=billIso(d);if(!billBreak(p.id,date)&&!billCancelled(p.id,s.id,date)){let hrs=billHours(s.start_time,s.end_time),net=s.rate==null?0:Number(s.rate)*hrs,vr=s.vat_applicable?vatRate(hirerId):0;out.push({kind:'Recurring',date,start:String(s.start_time||'').slice(0,5),end:String(s.end_time||'').slice(0,5),title:s.title||p.name||'Recurring booking',hours:hrs,rate:s.rate,net,vat:net*vr/100,total:net*(1+vr/100),vat_applicable:!!s.vat_applicable,source_id:s.id,programme_id:p.id})} } d=new Date(d.getTime()+DAY)}
  })
 });
 B.filter(x=>x.hirer_id===hirerId&&x.site_id===siteId&&x.booking_date>=from&&x.booking_date<=to&&x.status!=='cancelled'&&(x.charge_type||'chargeable')==='chargeable').forEach(x=>{let hrs=bookingHours(x),net=x.rate==null?0:Number(x.rate)*hrs,vr=x.vat_applicable?vatRate(hirerId):0;out.push({kind:'Single',date:x.booking_date,start:String(x.start_time||'').slice(0,5),end:String(x.end_time||'').slice(0,5),title:x.title||'Booking',hours:hrs,rate:x.rate,net,vat:net*vr/100,total:net*(1+vr/100),vat_applicable:!!x.vat_applicable,source_id:x.id})});
 return out.sort((a,b)=>a.date.localeCompare(b.date)||a.start.localeCompare(b.start))
}
function totals(rows){return rows.reduce((a,r)=>({net:a.net+r.net,vat:a.vat+r.vat,total:a.total+r.total,hours:a.hours+r.hours}),{net:0,vat:0,total:0,hours:0})}
function statusLabel(s){return ({draft:'Draft',pool_manager_checked:'Pool Manager checked',lettings_manager_approved:'Lettings Manager approved',ready:'Ready for invoice',invoiced:'Invoiced',paid:'Paid',adjustment_required:'Adjustment required'})[s]||s||'Draft'}
function statusClass(s){return s==='adjustment_required'?'danger':(['lettings_manager_approved','ready','invoiced','paid'].includes(s)?'good':s==='pool_manager_checked'?'warn':'')}
async function loadBillingData(){
 let [b,e2]=await Promise.all([sb.from('school_invoice_batches').select('*').order('usage_month',{ascending:false}),sb.from('school_invoice_batch_events').select('*').order('created_at',{ascending:false})]);
 BILL_BATCHES=b.data||[];BILL_EVENTS=e2.data||[];
}
function batchFor(siteId,hirerId,month){let u=monthBounds(month).usage_month;return BILL_BATCHES.find(b=>b.site_id===siteId&&b.hirer_id===hirerId&&b.usage_month===u)}
async function logBill(batch,eventType,oldStatus,newStatus,oldNet,newNet,notes){
 await sb.from('school_invoice_batch_events').insert({batch_id:batch.id,actor_user_id:P.id,event_type:eventType,old_status:oldStatus||null,new_status:newStatus||null,old_net_amount:oldNet??null,new_net_amount:newNet??null,notes:notes||null})
}
async function ensureBatch(siteId,hirerId,month){
 let rows=monthRows(hirerId,siteId,month),t=totals(rows),existing=batchFor(siteId,hirerId,month);
 if(existing){
   let changed=Math.abs(Number(existing.net_amount||0)-t.net)>.005||Math.abs(Number(existing.vat_amount||0)-t.vat)>.005;
   let wasApproved=['pool_manager_checked','lettings_manager_approved','ready','invoiced','paid'].includes(existing.status);
   let nextStatus=changed&&wasApproved?'adjustment_required':existing.status;
   let upd={net_amount:t.net,vat_amount:t.vat,total_amount:t.total,updated_at:new Date().toISOString()};
   if(nextStatus!==existing.status)upd.status=nextStatus;
   let {data,error}=await sb.from('school_invoice_batches').update(upd).eq('id',existing.id).select().single();if(error)throw error;
   if(changed)await logBill(data,nextStatus==='adjustment_required'?'adjustment_required':'recalculated',existing.status,nextStatus,Number(existing.net_amount||0),t.net,nextStatus==='adjustment_required'?'Calculated booking total changed after review/approval.':'Monthly statement recalculated.');
   return data
 }
 let {data,error}=await sb.from('school_invoice_batches').insert({site_id:siteId,usage_month:monthBounds(month).usage_month,hirer_id:hirerId,net_amount:t.net,vat_amount:t.vat,total_amount:t.total,status:'draft'}).select().single();if(error)throw error;await logBill(data,'created',null,'draft',null,t.net,'Monthly pool hire statement created.');return data
}
window.prepareMonthlyBilling=async()=>{let month=$('billMonth')?.value,site=$('billSite')?.value;if(!month)return alert('Choose a month.');let pairs=[];H.forEach(h=>S.filter(s=>!site||s.id===site).forEach(s=>{if(monthRows(h.id,s.id,month).length)pairs.push([s.id,h.id])}));if(!pairs.length)return alert('There are no chargeable organisation bookings for this month.');try{for(let [sid,hid] of pairs)await ensureBatch(sid,hid,month);await loadBillingData();renderMonthlyBilling()}catch(err){alert(err.message||String(err))}};
window.billingAction=async(id,action)=>{
 let b=BILL_BATCHES.find(x=>x.id===id);if(!b)return;
 let old=b.status,upd={updated_at:new Date().toISOString()},etype='',notes='';
 if(action==='pool'){upd.status='pool_manager_checked';upd.pool_manager_checked_by=P.id;upd.pool_manager_checked_at=new Date().toISOString();upd.approved_net_amount=b.net_amount;upd.approved_vat_amount=b.vat_amount;upd.approved_total_amount=b.total_amount;etype='pool_manager_checked'}
 if(action==='lettings'){if(!['pool_manager_checked','adjustment_required'].includes(old))return alert('The Pool Manager must check this statement first.');upd.status='lettings_manager_approved';upd.lettings_manager_approved_by=P.id;upd.lettings_manager_approved_at=new Date().toISOString();upd.approved_net_amount=b.net_amount;upd.approved_vat_amount=b.vat_amount;upd.approved_total_amount=b.total_amount;etype='lettings_manager_approved'}
 if(action==='ready'){if(old!=='lettings_manager_approved')return alert('The Lettings Manager must approve this statement first.');upd.status='ready';etype='marked_ready'}
 if(action==='invoice'){let ref=prompt('Enter the invoice reference from the school accounts system:','');if(ref===null)return;if(!ref.trim())return alert('Enter an invoice reference.');upd.status='invoiced';upd.invoice_reference=ref.trim();upd.invoiced_at=new Date().toISOString();etype='marked_invoiced';notes='Invoice reference: '+ref.trim()}
 if(action==='reopen'){let reason=prompt('Reason for reopening/adjusting this statement:','');if(reason===null)return;if(!reason.trim())return alert('Enter the reason for the adjustment.');upd.status='adjustment_required';upd.last_adjustment_reason=reason.trim();upd.last_adjusted_by=P.id;upd.last_adjusted_at=new Date().toISOString();etype='reopened';notes=reason.trim()}
 let {data,error}=await sb.from('school_invoice_batches').update(upd).eq('id',id).select().single();if(error)return alert(error.message);await logBill(data,etype,old,upd.status,Number(b.net_amount||0),Number(data.net_amount||0),notes);await loadBillingData();renderMonthlyBilling()
};
window.viewBillingStatement=id=>{let b=BILL_BATCHES.find(x=>x.id===id);if(!b)return;let month=String(b.usage_month).slice(0,7),rows=monthRows(b.hirer_id,b.site_id,month),t=totals(rows),ev=BILL_EVENTS.filter(x=>x.batch_id===id);let body=`<div class=bill-statement-head><div><b>${e(hn(b.hirer_id))}</b><div class=muted>${e(sn(b.site_id))} · ${e(monthLabel(month))}</div></div><span class="bill-status ${statusClass(b.status)}">${e(statusLabel(b.status))}</span></div><table><thead><tr><th>Date</th><th>Session</th><th>Hours</th><th>Rate</th><th>Net</th><th>VAT</th><th>Total</th></tr></thead><tbody>${rows.map(r=>`<tr><td>${e(shortUk(r.date))}</td><td><b>${e(r.title)}</b><div class=muted>${e(r.start+'–'+r.end)} · ${e(r.kind)}</div></td><td>${r.hours.toFixed(2)}</td><td>${r.rate==null?'—':billMoney(r.rate)+'/hr'}</td><td>${billMoney(r.net)}</td><td>${billMoney(r.vat)}</td><td><b>${billMoney(r.total)}</b></td></tr>`).join('')||'<tr><td colspan=7 class=muted>No chargeable sessions.</td></tr>'}</tbody><tfoot><tr><th colspan=4>Calculated total</th><th>${billMoney(t.net)}</th><th>${billMoney(t.vat)}</th><th>${billMoney(t.total)}</th></tr></tfoot></table><h3 style="margin-top:18px">Review & adjustment history</h3>${ev.map(x=>`<div class=bill-event><b>${e(statusLabel(x.new_status)||x.event_type)}</b><span>${new Date(x.created_at).toLocaleString('en-GB')}</span><div>${e(x.notes||'')}</div>${x.old_net_amount!=null&&x.new_net_amount!=null&&Number(x.old_net_amount)!==Number(x.new_net_amount)?`<div class=muted>${billMoney(x.old_net_amount)} → ${billMoney(x.new_net_amount)}</div>`:''}</div>`).join('')||'<div class=muted>No review events recorded yet.</div>'}`;modal('Monthly pool hire statement',body,()=>{});$('ms').style.display='none'};
function billingControls(){let host=$('incomeSummary');if(!host)return null;let wrap=$('monthlyBilling');if(!wrap){wrap=document.createElement('div');wrap.id='monthlyBilling';wrap.className='monthly-billing';host.parentElement.appendChild(wrap)}let now=new Date(),def=`${now.getFullYear()}-${String(now.getMonth()+1).padStart(2,'0')}`;if(!wrap.dataset.ready){wrap.innerHTML=`<div class="term-top compact" style="margin-top:22px"><div><h2>Monthly Billing</h2><p class=muted>Review each organisation's monthly pool hire, approve it and hand the confirmed total to the school finance team.</p></div></div><div class="bill-toolbar card"><label>Month<input id=billMonth type=month value="${def}"></label><label>Site<select id=billSite></select></label><button class=p onclick="prepareMonthlyBilling()">Prepare / recalculate statements</button></div><div id=billList></div>`;wrap.dataset.ready='1';$('billMonth').onchange=renderMonthlyBilling;$('billSite').onchange=renderMonthlyBilling}let site=$('billSite'),v=site.value;site.innerHTML='<option value="">All sites</option>'+S.map(s=>`<option value="${s.id}">${e(s.name)}</option>`).join('');if([...site.options].some(o=>o.value===v))site.value=v;return wrap}
window.renderMonthlyBilling=function(){let wrap=billingControls();if(!wrap)return;let month=$('billMonth').value,site=$('billSite').value,usage=monthBounds(month).usage_month;let batches=BILL_BATCHES.filter(b=>b.usage_month===usage&&(!site||b.site_id===site)).sort((a,b)=>(hn(a.hirer_id)+sn(a.site_id)).localeCompare(hn(b.hirer_id)+sn(b.site_id)));$('billList').innerHTML=batches.map(b=>{let actions=[];if(['draft','adjustment_required'].includes(b.status))actions.push(`<button class=s onclick="billingAction('${b.id}','pool')">Pool Manager check</button>`);if(b.status==='pool_manager_checked')actions.push(`<button class=s onclick="billingAction('${b.id}','lettings')">Lettings Manager approve</button>`);if(b.status==='lettings_manager_approved')actions.push(`<button class=s onclick="billingAction('${b.id}','ready')">Ready for invoice</button>`);if(b.status==='ready')actions.push(`<button class=s onclick="billingAction('${b.id}','invoice')">Mark invoiced</button>`);if(['pool_manager_checked','lettings_manager_approved','ready','invoiced'].includes(b.status))actions.push(`<button class=link onclick="billingAction('${b.id}','reopen')">Reopen / adjustment</button>`);return `<div class=bill-row><div><b>${e(hn(b.hirer_id))}</b><div class=muted>${e(sn(b.site_id))}</div></div><div><span class="bill-status ${statusClass(b.status)}">${e(statusLabel(b.status))}</span>${b.last_adjustment_reason?`<div class="muted bill-adjust">${e(b.last_adjustment_reason)}</div>`:''}</div><div class=bill-values><span>Net <b>${billMoney(b.net_amount)}</b></span><span>VAT <b>${billMoney(b.vat_amount)}</b></span><span>Total <b>${billMoney(b.total_amount)}</b></span></div><div class=bill-actions><button class=s onclick="viewBillingStatement('${b.id}')">View statement</button>${actions.join('')}</div></div>`}).join('')||'<div class="card muted">No monthly statements have been prepared for this month yet. Click <b>Prepare / recalculate statements</b>.</div>'}
const baseIncome=renderIncomeSummary;
renderIncomeSummary=function(){baseIncome();(async()=>{await loadBillingData();renderMonthlyBilling()})()};
const st=document.createElement('style');st.textContent=`.monthly-billing{margin-top:18px}.bill-toolbar{display:flex;gap:10px;align-items:end;flex-wrap:wrap;margin-bottom:12px}.bill-toolbar label{min-width:180px}.bill-row{display:grid;grid-template-columns:minmax(180px,1.2fr) minmax(170px,.8fr) minmax(280px,1.1fr) minmax(280px,1.4fr);gap:14px;align-items:center;background:#fff;border:1px solid #dfe6eb;border-radius:12px;padding:13px 15px;margin:8px 0}.bill-status{display:inline-block;padding:5px 9px;border-radius:999px;background:#eef2f5;font-size:12px;font-weight:800}.bill-status.good{background:#e9f7ee;color:#21643a}.bill-status.warn{background:#fff6dd;color:#775b07}.bill-status.danger{background:#fff0f0;color:#9b2d2d}.bill-values{display:flex;gap:14px;flex-wrap:wrap}.bill-values span{font-size:12px;color:#657581}.bill-values b{display:block;color:#1f2d36;font-size:15px}.bill-actions{display:flex;gap:7px;align-items:center;justify-content:flex-end;flex-wrap:wrap}.bill-adjust{margin-top:4px}.bill-statement-head{display:flex;justify-content:space-between;gap:12px;align-items:center;margin-bottom:12px}.bill-event{border-left:3px solid #d9e3e9;padding:7px 10px;margin:7px 0;background:#f8fafb;border-radius:0 8px 8px 0}.bill-event>span{margin-left:10px;font-size:12px;color:#778792}@media(max-width:1000px){.bill-row{grid-template-columns:1fr 1fr}.bill-actions{justify-content:flex-start}}@media(max-width:650px){.bill-row{grid-template-columns:1fr}}`;document.head.appendChild(st);
})();
