(function(){
const baseRenderRecurringBookings=renderRecurringBookings;
const overviewDays=['Sun','Mon','Tue','Wed','Thu','Fri','Sat'];
function sessionPriceText(r){let ct=r.charge_type||'chargeable';if(ct==='internal_school_use')return 'Internal school use';if(ct==='free_of_charge')return 'Free of charge';if(r.rate==null)return 'Rate not set';return `£${Number(r.rate).toFixed(2)}/hr${r.vat_applicable?' + VAT':' · no VAT'}`}
function poolText(r){if(r.pool_use_type==='lanes')return `${r.lane_count||'?'} lane${Number(r.lane_count)===1?'':'s'}`;if(r.pool_use_type==='other')return 'Other pool allocation';return 'Whole pool'}
function groupedSessions(items){let m=new Map();items.forEach(r=>{let key=[String(r.start_time||'').slice(0,5),String(r.end_time||'').slice(0,5),(r.title||'Swimming lessons').trim(),r.charge_type||'chargeable',r.rate??'',!!r.vat_applicable,r.pool_use_type||'whole_pool',r.lane_count??''].join('|');if(!m.has(key))m.set(key,{sample:r,days:[]});m.get(key).days.push(Number(r.day_of_week))});return [...m.values()].sort((a,b)=>Math.min(...a.days)-Math.min(...b.days)||String(a.sample.start_time).localeCompare(String(b.sample.start_time)))}
function cardRows(){let q=($('rbSearch')?.value||'').trim().toLowerCase(),site=$('rbSite')?.value||'',org=$('rbOrg')?.value||'',status=$('rbStatus')?.value||'active';return G.filter(x=>{let active=x.active!==false;if(status==='active'&&!active)return false;if(status==='archived'&&active)return false;if(site&&x.site_id!==site)return false;if(org==='internal'&&x.hirer_id)return false;if(org&&org!=='internal'&&x.hirer_id!==org)return false;if(q&&!`${x.name||''} ${sn(x.site_id)} ${hn(x.hirer_id)||'school internal'}`.toLowerCase().includes(q))return false;return true}).sort((a,b)=>(sn(a.site_id)+hn(a.hirer_id)+(a.name||'')).localeCompare(sn(b.site_id)+hn(b.hirer_id)+(b.name||'')))}
function overviewFor(x){let sessions=RS.filter(r=>r.programme_id===x.id&&r.active!==false),breaks=BR.filter(r=>r.programme_id===x.id).sort((a,b)=>String(a.starts_on).localeCompare(String(b.starts_on))),ex=EX.filter(r=>r.programme_id===x.id).sort((a,b)=>String(a.exception_date).localeCompare(String(b.exception_date)));
let timetable=groupedSessions(sessions).map(g=>{let r=g.sample,ds=[...new Set(g.days)].sort((a,b)=>a-b).map(d=>overviewDays[d]).join(', ');return `<div class="rb-ov-row"><div class="rb-ov-main"><b>${e(ds)}</b><span>${String(r.start_time||'').slice(0,5)}–${String(r.end_time||'').slice(0,5)}</span><span>${e((r.title||'Swimming lessons').trim())}</span></div><div class="rb-ov-meta"><span>${e(poolText(r))}</span><span>${e(sessionPriceText(r))}</span></div></div>`}).join('')||'<div class="rb-ov-empty">No weekly sessions</div>';
let breakHtml=breaks.map(b=>`<div class="rb-ov-chip break"><b>${e(b.name||'Break')}</b><span>${shortUk(b.starts_on)}${b.ends_on&&b.ends_on!==b.starts_on?' → '+shortUk(b.ends_on):''}</span></div>`).join('')||'<span class="rb-ov-empty">No breaks</span>';
let exHtml=ex.map(z=>{let s=RS.find(r=>r.id===z.session_id);let label=s?`${overviewDays[Number(s.day_of_week)]} ${String(s.start_time||'').slice(0,5)}–${String(s.end_time||'').slice(0,5)}`:'All sessions';return `<div class="rb-ov-chip cancel"><b>${shortUk(z.exception_date)}</b><span>${e(label)}${z.notes?' · '+e(z.notes):''}</span></div>`}).join('')||'<span class="rb-ov-empty">No cancellations</span>';
return `<div class="rb-overview"><div class="rb-ov-section"><div class="rb-ov-title">Weekly timetable</div>${timetable}</div><div class="rb-ov-two"><div class="rb-ov-section"><div class="rb-ov-title">Breaks</div><div class="rb-ov-chips">${breakHtml}</div></div><div class="rb-ov-section"><div class="rb-ov-title">Cancellations</div><div class="rb-ov-chips">${exHtml}</div></div></div></div>`}
renderRecurringBookings=function(){baseRenderRecurringBookings();let host=$('rProg');if(!host)return;let rows=cardRows(),cards=[...host.querySelectorAll('.rb-item')];cards.forEach((card,i)=>{let x=rows[i];if(!x)return;let existing=card.querySelector('.rb-overview');if(existing)existing.remove();let summary=card.querySelector('.rb-summary');if(summary)summary.insertAdjacentHTML('afterend',overviewFor(x))})};
const st=document.createElement('style');st.textContent=`.rb-overview{border-top:1px solid #e3e9ef;padding:12px 16px 14px;background:#fbfcfe}.rb-ov-section{min-width:0}.rb-ov-title{font-size:12px;font-weight:800;text-transform:uppercase;letter-spacing:.04em;color:#53687a;margin:0 0 7px}.rb-ov-row{display:flex;justify-content:space-between;gap:12px;padding:7px 0;border-top:1px solid #edf1f4}.rb-ov-row:first-of-type{border-top:0}.rb-ov-main{display:flex;gap:10px;align-items:baseline;flex-wrap:wrap}.rb-ov-main b{min-width:92px}.rb-ov-main span:last-child{color:#526473}.rb-ov-meta{display:flex;gap:8px;flex-wrap:wrap;justify-content:flex-end;font-size:12px;color:#53687a}.rb-ov-meta span{background:#eef3f7;border-radius:999px;padding:3px 7px}.rb-ov-two{display:grid;grid-template-columns:1fr 1fr;gap:18px;margin-top:12px}.rb-ov-chips{display:flex;gap:6px;flex-wrap:wrap}.rb-ov-chip{display:inline-flex;gap:6px;align-items:center;border-radius:8px;padding:6px 8px;font-size:12px}.rb-ov-chip.break{background:#fff7e6;border:1px solid #f0dfb5}.rb-ov-chip.cancel{background:#fff0f0;border:1px solid #efcdcd}.rb-ov-chip span{color:#53687a}.rb-ov-empty{font-size:12px;color:#81909d}@media(max-width:800px){.rb-ov-two{grid-template-columns:1fr}.rb-ov-row{display:block}.rb-ov-meta{justify-content:flex-start;margin-top:5px}}`;document.head.appendChild(st);
})();
