(function(){
let RSTAFF=[];
window.RSTAFF=RSTAFF;
const rsMoney=v=>'£'+Number(v||0).toLocaleString('en-GB',{minimumFractionDigits:2,maximumFractionDigits:2});
const rsServiceName=x=>x.service_label||({lifeguard:'Lifeguard',swimming_teacher:'Swimming teacher',teacher:'Teacher',other:'Other staffing'})[x.service_type]||'Staffing';
const rsCustomerName=x=>x.customer_type==='external_hirer'?(hn(x.customer_hirer_id)||'External hirer'):(sn(x.site_id)||'School');
const rsSessionLabel=s=>s?`${['Sun','Mon','Tue','Wed','Thu','Fri','Sat'][Number(s.day_of_week)]} ${String(s.start_time||'').slice(0,5)}–${String(s.end_time||'').slice(0,5)}`:'All sessions in recurring booking';
async function loadRecurringStaffing(){let q=await sb.from('recurring_staffing_services').select('*').order('created_at');RSTAFF=q.data||[];window.RSTAFF=RSTAFF;return RSTAFF}
function timeHours(a,b){let x=String(a||'').split(':').map(Number),y=String(b||'').split(':').map(Number);if(x.length<2||y.length<2||Number.isNaN(x[0])||Number.isNaN(y[0]))return 0;return Math.max(0,(y[0]*60+y[1]-x[0]*60-x[1])/60)}
function ruleHours(x,session){return timeHours(x.start_time||session?.start_time,x.end_time||session?.end_time)}
function programmeStaffingHtml(pid){let rules=RSTAFF.filter(x=>x.programme_id===pid&&x.active!==false);return `<div class="rb-section"><div class="rb-section-head"><span>Frogs & Friends staffing</span><button class="s" onclick="editRecurringStaffing(null,'${pid}')">+ Add staffing rule</button></div>${rules.length?`<div class=staffing-rule-list>${rules.map(x=>{let s=RS.find(r=>r.id===x.session_id),hrs=ruleHours(x,s);return `<div class=staffing-rule><div><div class=staffing-rule-title>${e(rsServiceName(x))} × ${Number(x.staff_count||1)}</div><div class=staffing-rule-sub>${e(rsSessionLabel(s))}${x.start_time&&x.end_time?` · staffing ${e(String(x.start_time).slice(0,5))}–${e(String(x.end_time).slice(0,5))}`:' · follows booking time'}</div></div><div><span class=staffing-rule-badge>${e(rsCustomerName(x))}</span><div class=staffing-rule-sub>${x.customer_type==='external_hirer'?'F&F invoices hirer':'F&F invoices school'}</div></div><div class=staffing-rule-money><b>${rsMoney(x.hourly_rate)}/staff hr</b><div class=staffing-rule-sub>${s?hrs.toFixed(2)+' hr × '+Number(x.staff_count||1)+' staff':'Calculated per session'}</div></div><div class=staffing-rule-actions><button class=link onclick="editRecurringStaffing('${x.id}','${pid}')">Edit</button><button class=link onclick="deleteRecurringStaffing('${x.id}')">Delete</button></div></div>`}).join('')}</div>`:'<div class=rb-empty>No recurring staffing attached.</div>'}</div>`}
function injectStaffingSections(){document.querySelectorAll('.rb-item').forEach(item=>{let manage=item.querySelector('.rb-manage-grid');if(!manage||manage.querySelector('.staffing-added'))return;let button=[...item.querySelectorAll('button')].find(b=>(b.getAttribute('onclick')||'').includes('editProgramme('));if(!button)return;let m=(button.getAttribute('onclick')||'').match(/editProgramme\('([^']+)'\)/);if(!m)return;let wrap=document.createElement('div');wrap.className='staffing-added';wrap.innerHTML=programmeStaffingHtml(m[1]);manage.appendChild(wrap)})}
window.rsSessionChanged=function(){let sid=$('rs1')?.value,s=RS.find(x=>x.id===sid);if($('rsUseBookingTime')?.checked){if($('rs5'))$('rs5').value=s?String(s.start_time||'').slice(0,5):'';if($('rs6'))$('rs6').value=s?String(s.end_time||'').slice(0,5):''}let note=$('rsSessionHelp');if(note)note.textContent=sid?'This staffing applies only to '+rsSessionLabel(s)+'.':'This staffing applies to every weekly session in this recurring booking.'}
window.rsTimeModeChanged=function(){let use=$('rsUseBookingTime')?.checked,wrap=$('rsTimeOverride');if(wrap)wrap.style.display=use?'none':'';if(use)rsSessionChanged()}
window.rsCustomerChanged=function(){let wrap=$('rs10wrap');if(wrap)wrap.style.display=$('rs9')?.value==='external_hirer'?'':'none'}
window.editRecurringStaffing=async function(id,pid,presetSessionId){
  if(!RSTAFF.length)await loadRecurringStaffing();
  let x=RSTAFF.find(z=>z.id===id)||{},p=G.find(z=>z.id===pid),sessions=RS.filter(s=>s.programme_id===pid&&s.active!==false);
  if(!p)return alert('Recurring booking could not be found. Please refresh and try again.');
  if(!sessions.length)return alert('Add at least one weekly session before adding staffing.');
  let stype=x.service_type||'lifeguard',cust=x.customer_type||'school',session=id?(x.session_id||''):(presetSessionId||sessions[0]?.id||''),sel=sessions.find(s=>s.id===session),useBookingTime=!x.start_time&&!x.end_time;
  modal(id?'Edit recurring staffing':'Add recurring staffing',`<label>Recurring booking<input value="${e((hn(p.hirer_id)||'School/Internal')+' — '+(p.name||''))}" disabled></label><label>Apply staffing to<select id=rs1 onchange="rsSessionChanged()"><option value="" ${session===''?'selected':''}>All sessions in this recurring booking</option>${sessions.map(s=>`<option value="${s.id}" ${s.id===session?'selected':''}>${e(rsSessionLabel(s))}</option>`).join('')}</select><div id=rsSessionHelp class=muted style="margin:2px 0 8px">${session?`This staffing applies only to ${e(rsSessionLabel(sel))}.`:'This staffing applies to every weekly session in this recurring booking.'}</div></label><label>Service type<select id=rs2><option value=lifeguard ${stype==='lifeguard'?'selected':''}>Lifeguard</option><option value=swimming_teacher ${stype==='swimming_teacher'?'selected':''}>Swimming teacher</option><option value=teacher ${stype==='teacher'?'selected':''}>Teacher</option><option value=other ${stype==='other'?'selected':''}>Other staffing</option></select></label><label>Service description<input id=rs3 value="${e(x.service_label||'')}"></label><label>Number of staff<input id=rs4 type=number min=1 step=1 value="${x.staff_count||1}"></label><label style="grid-column:1/-1"><span style="display:flex;align-items:center;gap:8px"><input id=rsUseBookingTime type=checkbox style="width:auto;margin:0" ${useBookingTime?'checked':''} onchange="rsTimeModeChanged()"> Use the booking session start/end time for staffing</span></label><div id=rsTimeOverride style="display:${useBookingTime?'none':'contents'}"><label>Staffing start<input id=rs5 type=time value="${String(x.start_time||sel?.start_time||'').slice(0,5)}"></label><label>Staffing end<input id=rs6 type=time value="${String(x.end_time||sel?.end_time||'').slice(0,5)}"></label></div><label>Charge per staff hour (£)<input id=rs7 type=number min=0 step=.01 value="${x.hourly_rate??''}"></label><label>VAT<select id=rs8><option value=false ${!x.vat_applicable?'selected':''}>No VAT</option><option value=true ${x.vat_applicable?'selected':''}>VAT applies</option></select></label><label>Charge Frogs & Friends service to<select id=rs9 onchange="rsCustomerChanged()"><option value=school ${cust==='school'?'selected':''}>School</option><option value=external_hirer ${cust==='external_hirer'?'selected':''}>Hiring organisation</option></select></label><label id=rs10wrap style="display:${cust==='external_hirer'?'':'none'}">Hiring organisation<select id=rs10><option value="">Select organisation</option>${opts(H,x.customer_hirer_id,z=>z.name)}</select></label><label>Starts on<input id=rs11 type=date value="${x.starts_on||p.starts_on||''}"></label><label>Ends on<input id=rs12 type=date value="${x.ends_on||p.ends_on||''}"></label><label>Notes<textarea id=rs13>${e(x.notes||'')}</textarea></label>`,async()=>{
    if(rs9.value==='external_hirer'&&!rs10.value)return alert('Select the hiring organisation to charge.');
    if(!$('rsUseBookingTime').checked&&(!rs5.value||!rs6.value))return alert('Enter the staffing start and end time, or use the booking session time.');
    let q={organisation_id:P.organisation_id,site_id:p.site_id,programme_id:pid,session_id:rs1.value||null,service_type:rs2.value,service_label:rs3.value||null,staff_count:Number(rs4.value||1),start_time:$('rsUseBookingTime').checked?null:(rs5.value||null),end_time:$('rsUseBookingTime').checked?null:(rs6.value||null),hourly_rate:Number(rs7.value||0),vat_applicable:rs8.value==='true',vat_rate:20,customer_type:rs9.value,customer_hirer_id:rs9.value==='external_hirer'?rs10.value:null,starts_on:rs11.value||null,ends_on:rs12.value||null,active:true,notes:rs13.value||null,created_by:x.created_by||P.id,updated_at:new Date().toISOString()};
    let res=id?await sb.from('recurring_staffing_services').update(q).eq('id',id):await sb.from('recurring_staffing_services').insert(q);
    if(res.error)return alert(res.error.message);
    closeM();await loadRecurringStaffing();renderRecurringBookings();
  });
}
window.deleteRecurringStaffing=async function(id){if(!confirm('Delete this recurring staffing rule?'))return;let q=await sb.from('recurring_staffing_services').delete().eq('id',id);if(q.error)return alert(q.error.message);await loadRecurringStaffing();renderRecurringBookings()}
const oldRenderRecurring=window.renderRecurringBookings;
window.renderRecurringBookings=function(){oldRenderRecurring();setTimeout(async()=>{await loadRecurringStaffing();injectStaffingSections()},0)};
})();