(function(){
const DAY=86400000;
function isoLocal(d){let y=d.getFullYear(),m=String(d.getMonth()+1).padStart(2,'0'),day=String(d.getDate()).padStart(2,'0');return `${y}-${m}-${day}`}
function parseDate(v){return new Date(v+'T12:00:00')}
function maxDate(a,b){return a>b?a:b} function minDate(a,b){return a<b?a:b}
function hoursBetween(a,b){let x=String(a||'00:00').split(':').map(Number),y=String(b||'00:00').split(':').map(Number);return Math.max(0,(y[0]*60+y[1]-x[0]*60-x[1])/60)}
function money(v){return '£'+Number(v||0).toLocaleString('en-GB',{minimumFractionDigits:2,maximumFractionDigits:2})}
function rangeDefaults(mode){let now=new Date(),from,to;if(mode==='year'){let y=now.getMonth()>=8?now.getFullYear():now.getFullYear()-1;from=new Date(y,8,1,12);to=new Date(y+1,7,31,12)}else if(mode==='week'){let d=new Date(now);let diff=(d.getDay()+6)%7;from=new Date(d.getFullYear(),d.getMonth(),d.getDate()-diff,12);to=new Date(from.getFullYear(),from.getMonth(),from.getDate()+6,12)}else{from=new Date(now.getFullYear(),now.getMonth(),1,12);to=new Date(now.getFullYear(),now.getMonth()+1,0,12)}return [isoLocal(from),isoLocal(to)]}
function reportingControls(){let host=$('incomeSummary');if(!host)return null;if(!$('reportControls')){let p=host.parentElement;let controls=document.createElement('div');controls.id='reportControls';controls.className='report-toolbar card';controls.innerHTML=`<label>Period<select id=repPeriod><option value=month>This month</option><option value=week>This week</option><option value=year>Academic year</option><option value=custom>Custom dates</option></select></label><label>From<input id=repFrom type=date></label><label>To<input id=repTo type=date></label><label>Site<select id=repSite></select></label><label>Organisation<select id=repOrg></select></label><button class=s id=repRefresh>Refresh</button>`;p.insertBefore(controls,host);let [f,t]=rangeDefaults('month');$('repFrom').value=f;$('repTo').value=t;$('repPeriod').onchange=()=>{let mode=$('repPeriod').value;if(mode!=='custom'){let r=rangeDefaults(mode);$('repFrom').value=r[0];$('repTo').value=r[1]}renderIncomeSummary()};['repFrom','repTo','repSite','repOrg'].forEach(id=>$(id).onchange=()=>{if(id==='repFrom'||id==='repTo')$('repPeriod').value='custom';renderIncomeSummary()});$('repRefresh').onclick=renderIncomeSummary}
let site=$('repSite'),org=$('repOrg'),sv=site.value,ov=org.value;site.innerHTML='<option value="">All sites</option>'+S.map(x=>`<option value="${x.id}">${e(x.name)}</option>`).join('');org.innerHTML='<option value="">All users</option><option value="internal">School/Internal</option>'+H.map(x=>`<option value="${x.id}">${e(x.name)}</option>`).join('');if([...site.options].some(o=>o.value===sv))site.value=sv;if([...org.options].some(o=>o.value===ov))org.value=ov;return {from:$('repFrom').value,to:$('repTo').value,site:site.value,org:org.value}}
function orgMatches(hirerId,filter){if(!filter)return true;if(filter==='internal')return !hirerId;return hirerId===filter}
function siteMatches(siteId,filter){return !filter||siteId===filter}
function isBreak(programmeId,date){return BR.some(b=>b.programme_id===programmeId&&b.starts_on<=date&&(b.ends_on||b.starts_on)>=date)}
function isCancelled(programmeId,sessionId,date){return EX.some(x=>x.programme_id===programmeId&&x.exception_date===date&&(!x.session_id||x.session_id===sessionId))}
function recurringOccurrences(cfg){let out=[];if(!cfg.from||!cfg.to||cfg.from>cfg.to)return out;G.filter(p=>p.active!==false&&siteMatches(p.site_id,cfg.site)&&orgMatches(p.hirer_id,cfg.org)&&p.starts_on<=cfg.to&&p.ends_on>=cfg.from).forEach(p=>{let start=maxDate(p.starts_on,cfg.from),end=minDate(p.ends_on,cfg.to);RS.filter(s=>s.programme_id===p.id&&s.active!==false).forEach(s=>{let d=parseDate(start),last=parseDate(end);while(d<=last){if(d.getDay()===Number(s.day_of_week)){let date=isoLocal(d);if(!isBreak(p.id,date)&&!isCancelled(p.id,s.id,date)){let hrs=hoursBetween(s.start_time,s.end_time),charge=s.charge_type||'chargeable',income=charge==='chargeable'&&s.rate!=null?Number(s.rate)*hrs:0;out.push({kind:'Recurring',date,site_id:p.site_id,hirer_id:p.hirer_id,name:p.name||s.title||'Recurring booking',hours:hrs,income,charge_type:charge})}}d=new Date(d.getTime()+DAY)}})});return out}
function singleOccurrences(cfg){return B.filter(x=>x.status!=='cancelled'&&x.booking_date>=cfg.from&&x.booking_date<=cfg.to&&siteMatches(x.site_id,cfg.site)&&orgMatches(x.hirer_id,cfg.org)).map(x=>{let hrs=bookingHours(x),charge=x.charge_type||'chargeable',income=charge==='chargeable'&&x.rate!=null?Number(x.rate)*hrs:0;return {kind:'Single',date:x.booking_date,site_id:x.site_id,hirer_id:x.hirer_id,name:x.title||'Booking',hours:hrs,income,charge_type:charge}})}
function userName(id){return hn(id)||'School/Internal'}
function summaryByUser(rows){let map=new Map();rows.forEach(r=>{let key=r.hirer_id||'internal';if(!map.has(key))map.set(key,{name:userName(r.hirer_id),hours:0,income:0,sessions:0});let z=map.get(key);z.hours+=r.hours;z.income+=r.income;z.sessions++});return [...map.values()].sort((a,b)=>b.income-a.income||b.hours-a.hours)}
renderIncomeSummary=function(){let host=$('incomeSummary');if(!host)return;let cfg=reportingControls();if(!cfg||!cfg.from||!cfg.to){host.innerHTML='<div class="note">Choose a reporting date range.</div>';return}if(cfg.from>cfg.to){host.innerHTML='<div class="err">The From date must be before the To date.</div>';return}let recurring=recurringOccurrences(cfg),single=singleOccurrences(cfg),all=[...recurring,...single];let hours=all.reduce((a,x)=>a+x.hours,0),income=all.reduce((a,x)=>a+x.income,0),chargeable=all.filter(x=>x.charge_type==='chargeable'),foc=all.filter(x=>x.charge_type==='free_of_charge'),internal=all.filter(x=>x.charge_type==='internal_school_use');let forecastRecurring=recurring.reduce((a,x)=>a+x.income,0),singleIncome=single.reduce((a,x)=>a+x.income,0),users=summaryByUser(all);
host.innerHTML=`<div class="income-grid report-kpis"><div class="income-card">Pool use<b>${hours.toFixed(1)} hrs</b><span>${all.length} session${all.length===1?'':'s'}</span></div><div class="income-card">Hire income<b>${money(income)}</b><span>Net, before any VAT</span></div><div class="income-card">Recurring forecast<b>${money(forecastRecurring)}</b><span>Breaks & cancellations removed</span></div><div class="income-card">Single booking income<b>${money(singleIncome)}</b><span>${single.length} booking${single.length===1?'':'s'}</span></div></div><div class="report-split"><div class="card"><div class="card-head"><b>Usage mix</b><span class="muted">${shortUk(cfg.from)} → ${shortUk(cfg.to)}</span></div><div class="usage-mix"><div><b>${chargeable.reduce((a,x)=>a+x.hours,0).toFixed(1)}</b><span>Chargeable hours</span></div><div><b>${foc.reduce((a,x)=>a+x.hours,0).toFixed(1)}</b><span>Free-of-charge hours</span></div><div><b>${internal.reduce((a,x)=>a+x.hours,0).toFixed(1)}</b><span>School/internal hours</span></div></div></div><div class="card"><div class="card-head"><b>Income & use by organisation</b></div><table><thead><tr><th>Organisation</th><th>Sessions</th><th>Hours</th><th>Net income</th></tr></thead><tbody>${users.map(u=>`<tr><td><b>${e(u.name)}</b></td><td>${u.sessions}</td><td>${u.hours.toFixed(1)}</td><td><b>${money(u.income)}</b></td></tr>`).join('')||'<tr><td colspan=4 class=muted>No pool use in this period.</td></tr>'}</tbody></table></div></div><div class="note report-note">Recurring forecast is calculated from the weekly timetable within the selected dates and excludes recorded breaks and cancellations. Free-of-charge and school/internal sessions count towards usage hours but not hire income.</div>`}
const st=document.createElement('style');st.textContent=`.report-toolbar{display:flex;gap:10px;align-items:end;flex-wrap:wrap;margin-bottom:14px}.report-toolbar label{min-width:145px}.report-toolbar input,.report-toolbar select{margin-top:4px}.report-kpis .income-card span{display:block;color:#6b7b88;font-size:12px;margin-top:4px}.report-split{display:grid;grid-template-columns:minmax(280px,.8fr) minmax(440px,1.5fr);gap:14px;margin-top:14px}.usage-mix{display:grid;grid-template-columns:repeat(3,1fr);gap:8px}.usage-mix>div{background:#f5f8fa;border-radius:10px;padding:12px;text-align:center}.usage-mix b{display:block;font-size:22px}.usage-mix span{font-size:12px;color:#687985}.report-note{margin-top:14px}@media(max-width:900px){.report-split{grid-template-columns:1fr}.usage-mix{grid-template-columns:1fr}}`;document.head.appendChild(st);
})();
