function newRecurringWizard(){
 let sessions=[],breaks=[],exceptions=[],breakMode='single',step=1;
 const draw=()=>{
   let body=`<div class="wizard-steps">${[1,2,3,4,5].map((n,i)=>`<span class="wizard-step ${step===n?'on':''}">${n}. ${['Details','Timetable','Pricing & pool use','Breaks & Exceptions','Review'][i]}</span>`).join('')}</div>`;
   if(step===1) body+=`<label>Site<select id=wSite>${opts(S,details.site_id||null,z=>z.name)}</select></label><label>Organisation<select id=wOrg><option value="" ${details.hirer_id?'':'selected'}>School/Internal</option>${opts(H,details.hirer_id||null,z=>z.name)}</select></label><label>Booking name<input id=wName value="${e(details.name||'')}" placeholder="e.g. Pool Hire 2026/27"></label><label>Start date<input id=wStart type=date value="${e(details.starts_on||'')}"></label><label>End date<input id=wEnd type=date value="${e(details.ends_on||'')}"></label><label>Notes<textarea id=wNotes>${e(details.notes||'')}</textarea></label>`;
   if(step===2) body+=`<div class="wizard-block"><h3>Weekly timetable</h3><p class="muted">Add one pattern for days that share the same time. You can add another pattern for a second session on the same day.</p><div class="wizard-days">${['Sun','Mon','Tue','Wed','Thu','Fri','Sat'].map((d,i)=>`<label><input type=checkbox name=wday value=${i}>${d}</label>`).join('')}</div><div class="cols"><label>Start<input id=wST type=time></label><label>End<input id=wET type=time></label></div><label>Description<input id=wDesc value="Swimming lessons"></label><button type=button class=s onclick="wizardAddSession()">+ Add pattern</button><div id=wSessionList></div></div>`;
   if(step===3) body+=`<div class="wizard-block"><h3>Pricing & pool allocation</h3><p class="muted">Set these separately for each weekly pattern.</p><div id=wPriceList></div></div>`;
   if(step===4) body+=`<div class="wizard-block"><h3>Breaks & Exceptions</h3><p class="muted">Use a break when all sessions stop. Use a session cancellation when only one specific weekly session should not run.</p>
<div class="booking-tabs" style="margin:10px 0 14px">
<button type=button class="booking-tab active" id=wModeSingle onclick="wizardBreakMode('single')">Single-day break</button>
<button type=button class="booking-tab" id=wModeRange onclick="wizardBreakMode('range')">Date-range break</button>
<button type=button class="booking-tab" id=wModeSession onclick="wizardBreakMode('session')">Cancel one session</button>
</div>
<div id=wBreakEditor></div>
<div id=wBreakList></div>
<div id=wExceptionList></div>
</div>`;
   if(step===5) body+=`<div class="wizard-review" id=wReview></div>`;
   body+=`<div class="wizard-actions">${step>1?'<button type=button class=s id=wBack>Back</button>':''}${step<5?'<button type=button class=p id=wNext>Next</button>':'<button type=button class=p id=wFinish>Save recurring booking</button>'}</div>`;
   $('mf').innerHTML=body;
   $('ms').style.display='none';
   if(step===2) renderWizardSessions();
   if(step===3) renderWizardPrices();
   if(step===4) renderWizardBreaks();
   if(step===5) renderWizardReview();
   if($('wBack'))$('wBack').onclick=()=>{captureWizard();step--;draw()};
   if($('wNext'))$('wNext').onclick=()=>{if(!captureWizard(true))return;step++;draw()};
   if($('wFinish'))$('wFinish').onclick=finishWizard;
 };
 let details={};
 window.wizardAddSession=()=>{let days=[...document.querySelectorAll('input[name=wday]:checked')].map(x=>Number(x.value));if(!days.length)return alert('Select at least one day.');if(!$('wST').value||!$('wET').value||$('wET').value<=$('wST').value)return alert('Enter a valid start and end time.');sessions.push({days,start:$('wST').value,end:$('wET').value,title:$('wDesc').value.trim()||'Swimming lessons',charge_type:'chargeable',rate:'',vat:false,pool_use_type:'whole_pool',lane_count:''});document.querySelectorAll('input[name=wday]').forEach(x=>x.checked=false);$('wST').value='';$('wET').value='';renderWizardSessions()};
 window.wizardRemoveSession=i=>{sessions.splice(i,1);renderWizardSessions()};
 window.wizardBreakMode=mode=>{breakMode=mode;renderBreakEditor()};
 window.wizardAddBreak=()=>{if(!$('wBF')?.value)return alert('Enter the break date.');let end=breakMode==='single'?$('wBF').value:($('wBT')?.value||$('wBF').value);if(end<$('wBF').value)return alert('The end date cannot be before the start date.');breaks.push({name:$('wBN').value.trim()||(breakMode==='single'?'Single-day break':'Break'),starts_on:$('wBF').value,ends_on:end});renderWizardBreaks();renderBreakEditor()};
 window.wizardRemoveBreak=i=>{breaks.splice(i,1);renderWizardBreaks()};
 window.wizardRefreshSessionChoices=()=>{let date=$('wXD')?.value,sel=$('wXS');if(!sel)return;let day=date?new Date(date+'T12:00:00').getDay():null;sel.innerHTML='<option value="">Choose session</option>'+sessions.map((s,i)=>({s,i})).filter(x=>day!==null&&x.s.days.includes(day)).map(x=>`<option value=${x.i}>${x.s.start}–${x.s.end} · ${e(x.s.title)}</option>`).join('');if(date&&sel.options.length===1)sel.innerHTML+='<option value="" disabled>No sessions scheduled on this date</option>'};
 window.wizardAddException=()=>{let date=$('wXD')?.value,sidx=Number($('wXS')?.value);if(!date)return alert('Choose the cancellation date first.');if(!Number.isInteger(sidx)||!sessions[sidx])return alert('Choose the session to cancel.');let day=new Date(date+'T12:00:00').getDay();if(!sessions[sidx].days.includes(day))return alert('That session does not run on the selected date.');exceptions.push({exception_date:date,session_index:sidx,notes:$('wXN')?.value.trim()||''});renderWizardBreaks();renderBreakEditor()};
 window.wizardRemoveException=i=>{exceptions.splice(i,1);renderWizardBreaks()};
 function renderWizardSessions(){let h=$('wSessionList');if(h)h.innerHTML=sessions.map((s,i)=>`<div class="wizard-session"><b>${s.days.map(d=>['Sun','Mon','Tue','Wed','Thu','Fri','Sat'][d]).join(', ')}</b><span>${s.start}–${s.end}</span><span>${e(s.title)}</span><button class=link onclick="wizardRemoveSession(${i})">Remove</button></div>`).join('')||'<div class="rb-empty">No patterns added yet.</div>'}
 function renderWizardPrices(){let h=$('wPriceList');if(!h)return;h.innerHTML=sessions.map((s,i)=>`<div class="wizard-block" style="margin:8px 0"><b>${s.days.map(d=>['Sun','Mon','Tue','Wed','Thu','Fri','Sat'][d]).join(', ')} · ${s.start}–${s.end}</b><div class=cols><label>Charge type<select data-i=${i} data-k=charge_type><option value=chargeable ${s.charge_type==='chargeable'?'selected':''}>Chargeable</option><option value=free_of_charge ${s.charge_type==='free_of_charge'?'selected':''}>Free of charge</option><option value=internal_school_use ${s.charge_type==='internal_school_use'?'selected':''}>Internal school use</option></select></label><label>Hourly rate (£/hour)<input data-i=${i} data-k=rate type=number min=0 step=.01 value="${s.rate}"></label><label>VAT<select data-i=${i} data-k=vat><option value=false ${!s.vat?'selected':''}>No VAT</option><option value=true ${s.vat?'selected':''}>VAT applies</option></select></label><label>Pool use<select data-i=${i} data-k=pool_use_type><option value=whole_pool ${s.pool_use_type==='whole_pool'?'selected':''}>Whole pool</option><option value=lanes ${s.pool_use_type==='lanes'?'selected':''}>Number of lanes</option><option value=other ${s.pool_use_type==='other'?'selected':''}>Other</option></select></label><label>Number of lanes<input data-i=${i} data-k=lane_count type=number min=1 step=1 value="${s.lane_count}"></label></div></div>`).join('')}
 function renderBreakEditor(){let h=$('wBreakEditor');if(!h)return;['wModeSingle','wModeRange','wModeSession'].forEach(id=>$(id)?.classList.remove('active'));$(breakMode==='single'?'wModeSingle':breakMode==='range'?'wModeRange':'wModeSession')?.classList.add('active');
   if(breakMode==='single')h.innerHTML=`<div class="wizard-break"><input id=wBN placeholder="Reason/name, e.g. Bank Holiday"><input id=wBF type=date><span></span><button type=button class=s onclick="wizardAddBreak()">Add single day</button></div>`;
   else if(breakMode==='range')h.innerHTML=`<div class="wizard-break"><input id=wBN placeholder="Break name, e.g. Christmas Holiday"><input id=wBF type=date><input id=wBT type=date><button type=button class=s onclick="wizardAddBreak()">Add date range</button></div>`;
   else h.innerHTML=`<div class="wizard-break"><input id=wXD type=date onchange="wizardRefreshSessionChoices()"><select id=wXS><option value="">Choose date first</option></select><input id=wXN placeholder="Reason / notes"><button type=button class=s onclick="wizardAddException()">Cancel session</button></div><div class="muted" style="margin-top:6px">Choose the date first. Only sessions that actually run on that day will then be available to cancel.</div>`;
 }
 function renderWizardBreaks(){renderBreakEditor();let h=$('wBreakList');if(h)h.innerHTML=`<h4 style="margin:14px 0 6px">Breaks</h4>`+(breaks.map((b,i)=>`<div class="wizard-session"><b>${e(b.name)}</b><span>${shortUk(b.starts_on)}</span><span>${b.ends_on===b.starts_on?'Single day':shortUk(b.ends_on)}</span><button class=link onclick="wizardRemoveBreak(${i})">Remove</button></div>`).join('')||'<div class="rb-empty">No breaks added.</div>');let x=$('wExceptionList');if(x)x.innerHTML=`<h4 style="margin:14px 0 6px">Individual session cancellations</h4>`+(exceptions.map((z,i)=>{let s=sessions[z.session_index];return `<div class="wizard-session"><b>${shortUk(z.exception_date)}</b><span>${s?s.days.map(d=>['Sun','Mon','Tue','Wed','Thu','Fri','Sat'][d]).join(', ')+' · '+s.start+'–'+s.end:'Session'}</span><span>${e(z.notes||'Cancelled')}</span><button class=link onclick="wizardRemoveException(${i})">Remove</button></div>`}).join('')||'<div class="rb-empty">No individual session cancellations added.</div>')}

 function renderWizardReview(){let h=$('wReview');if(!h)return;h.innerHTML=`<h3>${e(hn(details.hirer_id)||'School/Internal')}</h3><b>${e(details.name)}</b><p>${shortUk(details.starts_on)} → ${shortUk(details.ends_on)}</p><h4>Weekly timetable</h4>${sessions.map(s=>`<div>${s.days.map(d=>['Sun','Mon','Tue','Wed','Thu','Fri','Sat'][d]).join(', ')} · ${s.start}–${s.end} · ${s.pool_use_type==='lanes'?(s.lane_count+' lanes'):s.pool_use_type.replaceAll('_',' ')} · ${s.charge_type==='chargeable'?(s.rate?'£'+Number(s.rate).toFixed(2)+'/hr':'Rate not set'):s.charge_type.replaceAll('_',' ')}</div>`).join('')}<h4>Breaks</h4>${breaks.length?breaks.map(b=>`<div>${e(b.name)} · ${shortUk(b.starts_on)}${b.ends_on!==b.starts_on?' → '+shortUk(b.ends_on):' (single day)'}</div>`).join(''):'None added'}<h4>Individual session cancellations</h4>${exceptions.length?exceptions.map(z=>{let s=sessions[z.session_index];return `<div>${shortUk(z.exception_date)} · ${s?s.days.map(d=>['Sun','Mon','Tue','Wed','Thu','Fri','Sat'][d]).join(', ')+' '+s.start+'–'+s.end:'Session'}${z.notes?' · '+e(z.notes):''}</div>`}).join(''):'None added'}`}
 function captureWizard(validate=false){
   if(step===1){details={site_id:$('wSite').value,hirer_id:$('wOrg').value||null,name:$('wName').value.trim(),starts_on:$('wStart').value,ends_on:$('wEnd').value,notes:$('wNotes').value||null};if(validate&&(!details.site_id||!details.name||!details.starts_on||!details.ends_on)){alert('Complete the booking details and dates.');return false}}
   if(step===2&&validate&&!sessions.length){alert('Add at least one weekly timetable pattern.');return false}
   if(step===3){document.querySelectorAll('[data-i][data-k]').forEach(el=>{let s=sessions[Number(el.dataset.i)],k=el.dataset.k,v=el.value;if(k==='vat')v=v==='true';s[k]=v});if(validate){let bad=sessions.find(s=>s.pool_use_type==='lanes'&&(!s.lane_count||Number(s.lane_count)<1));if(bad){alert('Enter the number of lanes for lane bookings.');return false}}}
   return true
 }
 async function finishWizard(){captureWizard();let programme={site_id:details.site_id,academic_year_id:null,hirer_id:details.hirer_id,name:details.name,booking_type:details.hirer_id?'external_hire':'school_internal',external_category:details.hirer_id?'other':null,holiday_policy:null,starts_on:details.starts_on,ends_on:details.ends_on,notes:details.notes,created_by:P.id};let{data:pg,error}=await sb.from('recurring_programmes').insert(programme).select().single();if(error)return alert(error.message);let rows=[];sessions.forEach(s=>s.days.forEach(day=>rows.push({programme_id:pg.id,day_of_week:day,start_time:s.start,end_time:s.end,title:s.title,rate:s.charge_type==='chargeable'&&s.rate!==''?Number(s.rate):null,vat_applicable:s.charge_type==='chargeable'&&!!s.vat,charge_type:s.charge_type,foc_reason:null,pool_use_type:s.pool_use_type,lane_count:s.pool_use_type==='lanes'?Number(s.lane_count):null,active:true})));let createdSessions=[];if(rows.length){let r=await sb.from('recurring_programme_sessions').insert(rows).select();if(r.error)return alert('Booking created, but sessions need attention: '+r.error.message);createdSessions=r.data||[]}if(breaks.length){let r=await sb.from('recurring_programme_breaks').insert(breaks.map(b=>({...b,programme_id:pg.id,notes:null})));if(r.error)return alert('Booking created, but breaks need attention: '+r.error.message)}if(exceptions.length){let exRows=[];exceptions.forEach(z=>{let pattern=sessions[z.session_index];if(!pattern)return;let day=new Date(z.exception_date+'T12:00:00').getDay();let match=createdSessions.find(cs=>Number(cs.day_of_week)===Number(day)&&String(cs.start_time||'').slice(0,5)===pattern.start&&String(cs.end_time||'').slice(0,5)===pattern.end);if(match)exRows.push({programme_id:pg.id,session_id:match.id,exception_date:z.exception_date,exception_type:'cancelled',notes:z.notes||null})});if(exRows.length){let r=await sb.from('recurring_programme_session_exceptions').insert(exRows);if(r.error)return alert('Booking created, but session cancellations need attention: '+r.error.message)}}closeM();$('ms').style.display='';OPEN_PROG=pg.id;await load();setBookingTab('recurring')}
 modal('Create recurring booking','',()=>{});draw()
}
