const fs=require('fs');
const assert=require('assert');
const js=fs.readFileSync('commercial-enquiries-core.js','utf8');
const entry=fs.readFileSync('commercial-enquiries.js','utf8');
const archive=fs.readFileSync('commercial-enquiry-archive.js','utf8');
const index=fs.readFileSync('index.html','utf8');
const migration=fs.readFileSync('supabase/migrations/20260824000000_commercial_pool_enquiries.sql','utf8');
const fallback=fs.readFileSync('booking-scale.js','utf8');
assert(index.includes('commercial-enquiries.js'),'commercial enquiry runtime must be loaded');
assert(entry.includes('commercial-enquiries-core.js')&&entry.includes('commercial-enquiry-archive.js'),'entrypoint must load core and archive modules');
assert(js.includes("status:'converted'"),'conversion must mark the enquiry converted');
assert(js.includes("converted_booking_id:data.id"),'conversion must link the created booking');
assert(js.includes("if(!x.hirer_id)return alert"),'conversion must require an existing hirer');
assert(fallback.includes("'lettings_manager'")&&fallback.includes('Place hold')&&fallback.includes('Convert to booking')&&fallback.includes("'lost'"),'fallback rows must expose Lettings Manager enquiry actions');
assert(fallback.includes("typeof window.refreshCommercialEnquiries === 'function'")&&fallback.includes('await window.refreshCommercialEnquiries()'),'fallback must hand rendering to the core once it is ready');
assert(js.includes("isViewer()")&&js.includes("if(isViewer())return"),'operational viewer must not load commercial enquiries');
assert(archive.includes("opt.value='archived'")&&archive.includes("closeCommercialEnquiry(id,'archived')"),'completed enquiries must support non-destructive archive');
assert(migration.includes('has_site_access(site_id)'),'enquiry reads must be site scoped');
assert(migration.includes('can_edit_site_bookings(site_id)'),'enquiry writes must require booking edit permission');
assert(migration.includes("status in ('enquiry','held','converted','lost','cancelled')"),'base enquiry statuses must be constrained');
console.log('commercial enquiry workflow tests passed');
