const fs=require('fs');
const assert=require('assert');
const js=fs.readFileSync('commercial-enquiries.js','utf8');
const index=fs.readFileSync('index.html','utf8');
const migration=fs.readFileSync('supabase/migrations/20260824000000_commercial_pool_enquiries.sql','utf8');
assert(index.includes('commercial-enquiries.js'),'commercial enquiry runtime must be loaded');
assert(js.includes("status:'converted'"),'conversion must mark the enquiry converted');
assert(js.includes("converted_booking_id:data.id"),'conversion must link the created booking');
assert(js.includes("if(!x.hirer_id)return alert"),'conversion must require an existing hirer');
assert(js.includes("isViewer()")&&js.includes("if(isViewer())return"),'operational viewer must not load commercial enquiries');
assert(migration.includes('has_site_access(site_id)'),'enquiry reads must be site scoped');
assert(migration.includes('can_edit_site_bookings(site_id)'),'enquiry writes must require booking edit permission');
assert(migration.includes("status in ('enquiry','held','converted','lost','cancelled')"),'enquiry statuses must be constrained');
console.log('commercial enquiry workflow tests passed');
