const fs=require('fs');
const assert=require('assert');
const js=fs.readFileSync('commercial-enquiries-core.js','utf8');
const entry=fs.readFileSync('commercial-enquiries.js','utf8');
const archive=fs.readFileSync('commercial-enquiry-archive.js','utf8');
const index=fs.readFileSync('index.html','utf8');
const migration=fs.readFileSync('supabase/migrations/20260824000000_commercial_pool_enquiries.sql','utf8');
const visibilityMigration=fs.readFileSync('supabase/migrations/20260826134500_preserve_commercial_enquiry_creator_visibility.sql','utf8');
const visibleRpcMigration=fs.readFileSync('supabase/migrations/20260826135000_add_visible_commercial_enquiries_rpc.sql','utf8');
const recurringMigration=fs.readFileSync('supabase/migrations/20260827090000_recurring_enquiry_conversion_and_admin_delete.sql','utf8');
const fallback=fs.readFileSync('booking-scale.js','utf8');
assert(index.includes('commercial-enquiries.js'),'commercial enquiry runtime must be loaded');
assert(entry.includes('commercial-enquiries-core.js')&&entry.includes('commercial-enquiry-archive.js'),'entrypoint must load core and archive modules');
assert(js.includes("status:'converted'"),'conversion must mark the enquiry converted');
assert(js.includes("converted_booking_id:data.id"),'conversion must link the created booking');
assert(js.includes('convertCommercialEnquiryRecurring')&&js.includes("sb.rpc('convert_commercial_enquiry_to_recurring'"),'enquiries must support recurring conversion');
assert(recurringMigration.includes('converted_recurring_programme_id')&&recurringMigration.includes('for update'),'recurring conversion must link the programme and lock the enquiry');
assert(recurringMigration.includes('bookings_delete_admin')&&recurringMigration.includes("'owner_admin','operations_admin'"),'permanent booking deletion must be administrator-only');
assert(js.includes("if(!x.hirer_id)return alert"),'conversion must require an existing hirer');
assert(fallback.includes('Place hold')&&fallback.includes('Convert to booking')&&fallback.includes("'lost'"),'fallback rows must expose enquiry management actions when the site membership permits them');
assert(fallback.includes("site_memberships")&&fallback.includes("can_edit_bookings"),'fallback permissions must match the site-level booking permission used by enquiry writes');
assert(fallback.includes("ORGANISATION_WIDE_ENQUIRY_ROLES")&&fallback.includes("getCommercialAccessibleSites"),'only organisation-wide admins may bypass site membership and enquiry site options must be filtered');
assert(entry.includes("getCommercialAccessibleSites")&&js.includes("accessibleSites()"),'both enquiry editors and the enquiry filter must use accessible sites');
assert(js.includes("sb.from('site_memberships')")&&js.includes('ACCESSIBLE_SITE_IDS=new Set'),'the authoritative enquiry loader must load site membership context before rendering');
assert(js.includes('window.canManageCommercialSite'),'core actions must honour the site-level booking permission');
assert(fallback.includes("typeof window.refreshCommercialEnquiries === 'function'")&&fallback.includes('await window.refreshCommercialEnquiries()'),'fallback must hand rendering to the core once it is ready');
assert(js.includes("isViewer()")&&js.includes("if(isViewer())return"),'operational viewer must not load commercial enquiries');
assert(archive.includes("opt.value='archived'")&&archive.includes("closeCommercialEnquiry(id,'archived')"),'completed enquiries must support non-destructive archive');
assert(migration.includes('has_site_access(site_id)'),'enquiry reads must be site scoped');
assert(migration.includes('can_edit_site_bookings(site_id)'),'enquiry writes must require booking edit permission');
assert(migration.includes("status in ('enquiry','held','converted','lost','cancelled')"),'base enquiry statuses must be constrained');
assert(visibilityMigration.includes("'archived'")&&visibilityMigration.includes('(select auth.uid()) = created_by'),'completed enquiries must be archivable and remain visible to their creator');
assert(js.includes("sb.rpc('visible_commercial_enquiries')")&&fallback.includes("sb.rpc('visible_commercial_enquiries')"),'commercial enquiry readers must use the authenticated visibility function');
assert(visibleRpcMigration.includes('security definer')&&visibleRpcMigration.includes('revoke all')&&visibleRpcMigration.includes('grant execute')&&visibleRpcMigration.includes('can_edit_bookings = true'),'visibility function must enforce authenticated site-scoped access');
console.log('commercial enquiry workflow tests passed');
